From afc@klaatu.cc.purdue.edu Tue Jan 16 13:33:16 1990
Received: from klaatu.cc.purdue.edu by ernie.Berkeley.EDU (5.61/1.36)
	id AA09793; Tue, 16 Jan 90 13:33:09 -0800
Received: by klaatu.cc.purdue.edu (5.61/1.14)
	id AA01432; Tue, 16 Jan 90 16:32:51 -0500
Date: Tue, 16 Jan 90 16:32:51 -0500
From: afc@klaatu.cc.purdue.edu (Greg Flint)
Message-Id: <9001162132.AA01432@klaatu.cc.purdue.edu>
To: wilson@ernie.Berkeley.EDU
Subject: Some comments about PC Moria 4.873 aimed toward your Moria 5.0
Status: RO

You comment that Umoria 5.0 will have good balance because it will be
player tested before its release.  I'd be willing to volunteer to do
some of this beta testing.  I don't have lots of time to play but I find
moria to be a good way to unwind after a long day fighting more mundane
mosters such as Vaxes, Cybers and Suns.

A few opinions about PC Moria 4.873 that might influence Umoria 5.0:

 STATS
 -----
 * Once stats get to the 18/xx stage, I find that I can deal with almost
   anything non-hastened (except for MHD's and Green d/D's) because by then
   my HP's are usually quite high.  I can just hack away and usually come
   out on top.  If I have sufficient haste self, I tackle V's and L's.  If
   I don't, I phase door, teleport away or run for the stairs.  (The method
   depends on my character type, distance from the monster and equipment at
   hand.)

 * After I reach the 18/xx stage, the game degenerates in to a sequence of
	1) attack until I loose life levels,
	2) WOR to store level,
	3) buy more WOR and RLL, if available,
	4) kill time on level 1 if no RLL, then back to #3
       	5) WOR back to deepest level,
	6) go to #1".
   until I'm finally ready to go to level 50 of the dungeon.


 MONSTERS
 --------

 * It seems to take "forever" to go up the levels of 32+ because there is a
   big disparity between the value of monsters and the amount of points needed
   to rise to the next level.  I find myself looking for D's (and L's if I've
   the proper abilities and/or tools) and being bored by almost anything else
   -- and yet I'm not yet ready for Iggy or the big "B".


 MAGIC
 -----
 * Maybe I've been lucky, but I've always been able to find some "see
   invisible" item early (about Banshee dungeon level).  This makes G's, L's,
   etc a lot easier (see the earlier comment on my playing sequence.)

 * When playing as a mage and reaching about level 29 where I gain fire ball,
   I find that I've reached the peak in spells.  Of the two spells after that,
   I've never used WOD and find Genocide so powerful that it seems like
   cheating.


 STORES and MONEY
 ----------------

 * Money is an issue early, but once I get to about 10,000, I never need to
   worry about money again -- for two reasons.  The scrolls, potions, staves
   and the like are cheap (relative to 10K gold).  The weapons that are HA,
   DF, etc almost never appear so even though they are expensive, I never
   seem to need the money.

 * It would be nice to know how may of a given item are in a store.  This
   would help with questions such as "should I buy now or wait and chance
   that it (they?) are gone next time?" or "can I buy him out in the hopes
   of getting better stock next time?".


 MAGE SPELLS
 -----------

 * The two recharge and the three sleep spells seem redundant (especially
   the latter).  I usually ignore the Level I recharge and Levels I and II
   sleep spells because I need more offensive weaponry (spells).  By the time
   I get around to learning these low level spells (because I've moved up
   a mage level and you've got to pick something), I really don't need them.

 * I don't know what I'd suggest, but I'd like to see some other spells in
   place of the ones listed above -- especially some after level 29.

 * How about spells being fixed in terms of there letter?  Nothing is more
   painful than forgetting that I've added spell "b" thereby making spell "e"
   spell "f" and wasting a bunch of mana and maybe allowing a monster a free
   hit.


 MAP
 ---

 * I find the reduced map a help in speeding up the game.  I favor anything
   that speeds up the game at no penalty me.  (For example, using "H" to
   "run" in place of lots of h's is a no cost plus.  I would not want to be
   penalized for "running" since all I'm doing is speeding up the game, not
   trying to "tire out" the character.)

------------------------------------------------------------------------------
Greg Flint 	  Math G-169   (317) 494-1787   UUCP:  purdue!klaatu.cc!afc
  Purdue Univ.	  Purdue University	    INTERNET:  afc@klaatu.cc.purdue.edu
  Computing Ctr.  West Lafayette, IN 47907    BITNET:  flint@purccvm.bitnet

From qqc@h.cc.purdue.edu Thu Jan 18 13:54:52 1990
Received: from h.cc.purdue.edu by ernie.Berkeley.EDU (5.61/1.36)
	id AA09437; Thu, 18 Jan 90 13:54:47 -0800
Received: by h.cc.purdue.edu (5.61/1.14)
	id AA15380; Thu, 18 Jan 90 16:54:08 -0500
Date: Thu, 18 Jan 90 16:54:08 -0500
From: qqc@h.cc.purdue.edu (Dale Forsyth)
Message-Id: <9001182154.AA15380@h.cc.purdue.edu>
To: wilson@ernie.Berkeley.EDU
Subject: program comments
Status: RO


Jim Wilson:  As I perceive you as the author/programmer now associated
with moria, I have several comments to make, in light of messages you have
posted in the past about the program.  I use the ibm-pc version 4.873, but
expect my comments apply universally.  All the following is, of course, only
one person's opinion.
   I'm almost ashamed to admit how much I've used the program -- suffice to
say I consider myself VERY experienced.  I think I could win with ANY
character, but I would not have the patience to do so.
   I consider the ONLY reason to use the program is for my own enjoyment.
Any cheating I do is only to myself, for myself, and affects no one else; of
course mine isn't a multi-user machine, for which you are concerned.
   In my opinion, a mage is a reasonable and fun character.  I don't think it
should be necessary to change it's balance.  A priest (current character) is
ok EXCEPT that it needs an identify spell.  Either that or the shops MUST keep
identify spells stocked.  Since they do not in my version, I would quit this
character as NOT FUN anymore, except that I use wizard mode and cheat on this
point.
  I do NOT consider the 'triangle dance' around monsters a bad thing.  I think
there SHOULD be a way to outdo monsters that are bigger and badder than you,
if you have patience.
  The shops is an area that needs improvement; they should contain better and
better things as one's level increases.  After a while there becomes NO REASON
to return topside and accumulation of gold becomes moot.  It would stay more
FUN if you could BUY that HA weapon, even at 300,000 gp, when you have only
175,000 gp.  But really good stuff never appears in MY shops.
   Endless repetition of mundane tactics that you know, waiting for something
you NEED, is NOT FUN.  A little is ok, month's of my life that way is NOT FUN.
   Characters beyond the BALROG would be possible, as for example Mordred from
Mordor (Lord of the Rings), the Ring Wraiths, etc.  I think reincarnation,
perhaps with some penalty, would be I think reasonable.  (Me, I cheat with
backups, to learn, try things that if I knew I couldn't get back I just
wouldn't do, and therefore wouldn't have that particular fun, etc).
   If one thing is over-powerful, it's perhaps bashing for good characters.
When I am REALLY ready to take on the balrog, (not try it for FUN with a worse
character), I accomplish his demise, fully loaded with mana, equipment, etc,
none of which I need or use, and he dies without ever touching me.  Of course
this takes searching for months for enough speed, but bashing is the secret
(as I know you know) and reduces the game to trivial at that point.  (3 AMHD's
at one time, all always stunned, none ever hurting you; that's an example).

  My main points in this letter are Priests and others need Identify or stores
must keep scrolls, to be fun, and stores should stock better, more expensive
things as one progresses.
             Thanks for maintaining such a good program, one of the most
             addictive I know.
Dale Forsyth (45 yr-old game addict)  qqc@h.cc.purdue.edu

From ucbvax!tut.cis.ohio-state.edu!cs.utexas.edu!yale!cs.yale.edu
Status: RO

Article 4187 of rec.games.moria:
Path: ucbvax!tut.cis.ohio-state.edu!cs.utexas.edu!yale!cs.yale.edu!
>From: berman-andrew@CS.Yale.EDU (Andrew Berman)
Newsgroups: rec.games.moria
Subject: Possible Enhancements
Message-ID: <12615@cs.yale.edu>
Date: 24 Jan 90 03:52:46 GMT
Sender: news@cs.yale.edu
Reply-To: berman-andrew@CS.Yale.EDU (Andrew Berman)
Organization: Yale University Computer Science Dept, New Haven CT  06520-2158
Lines: 47


I've been playing moria off and on for several years, only recently with
version 4.87.  I have some suggestions which I'd like input on.  Most of
them would make the game *harder*, but would also increase the power
and attractiveness of some classes, like the fighter, which don't get
used as often.

The first suggestion is to give fighters limited poison
immunity.  Let them take a % damage which diminishes with their level,
up to, say 1/2 damage for a level 39 character.  So they won't get
blown away like other characters by AMHD.  They have enough problems
as it is.  And it's somewhat consistent- a fighters training may
include ducking blasts, holding their breath, keeping their skin from
being exposed, etc...

The second suggestion is to limit the power of the "cure poison" *spell*
of the mages and priests. Right now, you can fight a black mamba and
kill it without looking at your stats, because a simple relatively low
level spell will eliminate any future problems.  Keep the potion as
currently powered, though.



The third suggestion is to limit weapons and Armor based on character class,
like in D & D.  I see no reason to allow a Priest full use of an Executioner's
sword, no matter what his/her strength/dex.  If a Priest uses an edged
weapon,  have some sort of minus.  If a Mage tries to cast a spell through
Plate Armor, decrease chance of success. If a Rogue uses a dagger, give
a +3 to hit bonus.  Fighters and Paladins can use anything.  Rangers get
double damage with bows. Something like that.

My fourth suggestion is to limit max stats based on character race and
maybe on character class.

The point of the previous two suggestions is to eliminate the
demigodlike character, a 250 hitpoint, 4-hits-per-round-with-a-Beaked-Axe,
armor class of 58 character elven mage.

My fifth suggestion is to allow "disenchanting" creatures to occasionally
zap an ego weapon, low probability, but maybe "you hear your longsword scream
in agony" as it goes from an HA to zip.

My sixth suggestion is to give critical hits to monsters.  Let a Bezerker
occasionally get a good one in for triple damage.  Let a touch have
a 5% chance of being a grasp for double drain..

Any comments?


From ucbvax!decwrl!lll-winken!uwm.edu!cs.utexas.edu!tut.cis.ohio-state.edu
Status: RO

Article 4188 of rec.games.moria:
Path: ucbvax!decwrl!lll-winken!uwm.edu!cs.utexas.edu!tut.cis.ohio-state.edu
>From: mf2t+@andrew.cmu.edu (Matthew David Fletcher)
Newsgroups: rec.games.moria
Subject: Re: Possible Enhancements
Message-ID: <YZjHVGi00XM101NVNs@andrew.cmu.edu>
Date: 24 Jan 90 05:08:34 GMT
References: <12615@cs.yale.edu>
Organization: Carnegie Mellon, Pittsburgh, PA
Lines: 35
In-Reply-To: <12615@cs.yale.edu>

berman-andrew@CS.Yale.EDU (Andrew Berman) writes:

>The first suggestion is to give fighters limited poison
>immunity.  Let them take a % damage which diminishes with their level,
>up to, say 1/2 damage for a level 39 character.  So they won't get
>blown away like other characters by AMHD.  They have enough problems
>as it is.  And it's somewhat consistent- a fighters training may
>include ducking blasts, holding their breath, keeping their skin from
>being exposed, etc...
>
>The second suggestion is to limit the power of the "cure poison" *spell*
>of the mages and priests. Right now, you can fight a black mamba and
>kill it without looking at your stats, because a simple relatively low
>level spell will eliminate any future problems.  Keep the potion as
>currently powered, though.

My current character is a twenty third level half-troll warrior.  The
only time I've come close to dying while being poisoned was when the
Stone Giant came up and started pounding me half way through.  Certain
races are naturally suited to certain classes by virtue of their
beginning stats.

Are mages capable of casting spells while afraid.  If so, a natural
resistance to fear would make it more even.  A ghost almost killed me a
while ago, because I couldn't attack it.

>My fifth suggestion is to allow "disenchanting" creatures to occasionally
>zap an ego weapon, low probability, but maybe "you hear your longsword scream
>in agony" as it goes from an HA to zip.

This could be rather expensive, considering the cost of all the computer
equipment that would be destroyed when a person's dagger (HA) (+8,+8)
gets zapped.

				Fletch


From ucbvax!tut.cis.ohio-state.edu!zaphod.mps.ohio-state.edu!unix.cis.p
Status: RO

Article 4193 of rec.games.moria:
Path: ucbvax!tut.cis.ohio-state.edu!zaphod.mps.ohio-state.edu!unix.cis.
>From: dtate@unix.cis.pitt.edu (David M Tate)
Newsgroups: rec.games.moria
Subject: Re: Possible Enhancements
Message-ID: <21833@unix.cis.pitt.edu>
Date: 24 Jan 90 17:00:57 GMT
References: <12615@cs.yale.edu>
Reply-To: dtate@unix.cis.pitt.edu (David M Tate)
Organization: Univ. of Pittsburgh, Comp & Info Services
Lines: 35

Andrew Berman lists a number of possible enhancements for later versions of
Moria.  Some of them, I think, bear serious consideration.

In particular, I think that the idea of distinguishing various character
classes even more sharply is a good one.  I agree wholeheartedly that the only
weapons usable by a priest should be mace/morningstar/hammer/club/flail types.
No one but a fighter, paladin, or ranger should be able to wield a 2-handed
sword or Executioner's Sword.  No matter how strong a mage gets, he should not
be able to fight effectively with anything heavy, nor able to cast spells
effectively while wearing heavy armor.

One way to reduce the mage/ranger advantage would be to implement a "setup
cost" for the switch between magic mode and fighting mode: you can't cast a
spell in the round immediately following a slash/fire move.  This makes some
sense, as one would in general have to "prepare" a spell before casting it.
Similarly, one would expect the act of praying to take some finite time.
(For that matter,eating should take some time--a character interrupted while
eating would have the option of finishing the meal (while getting stomped) or
abandoning it (in which case the remainder is lost--trampled in battle, or
some such).

One touch of realism that I would like to see is more more NPC's to pick up
things.  I know this can be done, because ghosts do it already.  Can you
really imagine a hobgoblin coming into a room and *not* picking up the gold
and gems?  This would add the challenge of preserving items to the character.

Similarly, why can't you get your stolen gold back from a dead rogue?  What
did he do with it?  Hide it?  If you're a rogue yourself, you should be able
to (a) keep him from picking your pocket, and (b) find where he hid it.

Just a few ramblings...

--
==============================================================================
          David M. Tate        | "I do not know which to prefer: the beauty
    dtate@unix.cis.pitt.edu    |  of inflections, or the beauty of innuendoes;
                               |  the blackbird whistling, or just after..."


From 73230.224@compuserve.com Tue Jan 30 11:46:30 1990
Received: from saqqara.cis.ohio-state.edu by ernie.Berkeley.EDU (5.61/1.36)
	id AA23367; Tue, 30 Jan 90 11:46:14 -0800
Received: by saqqara.cis.ohio-state.edu (5.61/4.891221)
	id AA09041; Tue, 30 Jan 90 14:45:48 -0500
Date: 30 Jan 90 12:41:49 EST
From: Curtis McCauley <73230.224@CompuServe.COM>
To: <wilson@ernie.Berkeley.EDU>
Subject: Umoria 5.0.13 disks mailed
Message-Id: <"900130174148 73230.224 EHA20-1"@CompuServe.COM>
Status: RO

To: >INTERNET:wilson@ernie.Berkeley.EDU
I mailed you the sources either Monday or Tuesday of last week.  I can't
remember which day for sure.  I used regular mail, so it may take some time.
The mailing required two diskettes, one for the source, the other for a
compiled version of the game.  Do you have access to MPW 3.0?  You will need
it to compile.  I don't think that THINK C could be used very easily in place
of MPW.  I rely pretty heavily on the MPW environment to make the program.

While I'm thinking about it, there are a couple of principles which, if
observed in all parts of the code, would make the mac port easier and less
of a hack:

1)  Don't modify a variable which is initialized in its declaration (e.g.,
"int foo_flag = TRUE").  I had to try to find all of these in order to make
the game restartable.

2)  Don't rely on the value of a variable which is not initialized in its
declaration being zero.  For example, get_panel() forces the panel to be
redrawn the first time it is called in the course of a game because
panel_[row/col]_[min/max] are all zero.  In the mac version, when the game is
restarted, these variables have the values left over from the previous game.
I do with them what I do with the variables which fall under 1 above:  I keep
their "initialized" value in a resource and restore them each time a game is
restarted.

3)  (This follows a fortiori from 1 above.)  Don't modify a private variable
which is initialized in its declaration.  These I had to move from the source
files in which they were declared to variables.c and externs.h in order to
make them accessible for the routines which build the restart resource and
copy the saved data when a new game is started.

Admittedly, there is some inconvience involved in following these rules.  It's
a judgement call.

The version I have given you "hilights" the veins instead of using '%'.  I
didn't discover that you had given up on hilighting until after I had ported
io.c to allow it.  So I figured I'd leave it in.  I discovered after I had
sent you the game that this causes the map command to screw up because it
doesn't know how to handle -'#'.  What do you think?  Remove the hilighting
capability or fix the map command to handle it?

You might want to consider the possibility of having two mac file types for
save files:  one for living characters, another for dead characters' memories.
This way the two files will be distinguishable by their icons.  (Perhaps a
tombstone as the latter type of icon.)

Do we want to get a new application signature from Apple?  I'd prefer not to,
but there likely will be problems for people who try to keep the old version
around on their disks.  For example, I am not certain which program will come
up if the user double clicks on a save file from the finder when he has both
copies of the game on his disk.  Maybe this can be handled by simply telling
the player to throw away his old version in the mac help text.

I do not like the way the game "flows" at the end, particularly the standard
file dialog which prompts for saving the player's memories.  It seems kind of
intrusive.  I do not know how things will change when the top ten is added.
Also, there is a problem with the prompt in this dialog box.  In save_char() I
try to say "Save your memories as:" instead of "Save the game as:" when I
think the player has died or quit.  This doesn't always work right.  Sometimes
it says "memories" when it should say "game".  This always happens when ^X is
used to save the game.  I have fixed that problem since I sent you the source.
Another problem remains:  I rely upon the variable death to decide which
prompt to choose.  This will not work when the player quits the character.
Death is not set, yet only the memories will get saved, right?  In the version
you have, I have the two prompts switched in save_char().  So, you get the
"memories" prompt when you quit and the "game" prompt when you are killed.

Finally, do female dwarves really have beards?  Ugh.

-Curtis (73230.224@compuserve.com)


From chinet!saj@gargoyle.uchicago.edu Mon Feb  5 23:29:25 1990
Received: from gargoyle.uchicago.edu by ernie.Berkeley.EDU (5.61/1.36)
	id AA00727; Mon, 5 Feb 90 23:29:21 -0800
Received: by gargoyle.uchicago.edu (5.59/1.14)
	id AA06383; Tue, 6 Feb 90 01:28:53 199
Received: by chinet.chi.il.us (/\=-/\ Smail3.1.18.1 #18.65)
	id <m0gvOff-0002kbC@chinet.chi.il.us>; Tue, 6 Feb 90 00:27 CST
Message-Id: <m0gvOff-0002kbC@chinet.chi.il.us>
From: saj@chinet.chi.il.us (Stephen Jacobs)
Subject: Source arrived today
To: ernie.Berkeley.EDU!wilson@gargoyle.uchicago.edu  (James E. Wilson)
Date: Tue, 6 Feb 90 0:27:26 CST
In-Reply-To: <9002020111.AA22413@ernie.Berkeley.EDU>; from "James E. Wilson"
X-Mailer: ELM [version 2.2 PL16]
Status: RO

The source arrived today.  Thanks.  I've barely begun to scan it, but I'd
guess that there shouldn't be any special problems bringing it up on the
ST.  One immediate suggestion: the Mark Williams C compiler defines the
macro GEMDOS, and defines the macro __STDC__ to be 0.  Using those as
conditions could make recognition of the situation automatic.

                                     Steve J.


