From boyne@hplvla.hp.com Tue Feb 27 08:03:46 1990
Received: from hp-sde.sde.hp.com by ernie.Berkeley.EDU (5.61/1.36)
	id AA19235; Tue, 27 Feb 90 08:03:44 -0800
Received: from hp-lvld.lvld.hp.com by hp-sde.sde.hp.com with SMTP
	(15.11.1.3/15.5+IOS 3.13) id AA03131; Tue, 27 Feb 90 08:03:15 pst
Received: from hplvla.HP.COM by hplisa.lvld.hp.com; Tue, 27 Feb 90 09:04:05mst
Received: from hplvre.HP.COM by hplvla.HP.COM; Tue, 27 Feb 90 09:04:43 mst
Received: by hplvre.HP.COM; Tue, 27 Feb 90 09:04:41 mst
Date: Tue, 27 Feb 90 09:04:41 mst
From: Art Boyne <boyne@hplvla.hp.com>
Message-Id: <9002271604.AA19981@hplvre.HP.COM>
To: wilson@ernie.Berkeley.EDU
Subject: Re: Hmmmmm (actually enchanting plusses)
Status: RO


> >	I have an odd little question to ask...  how does one increase the
> > first `plus' on a pick or shovel?  The two enchantment scrolls (Damage and
> > To-Hit) seem to increase the second set of pluses, and have no effect on
> > the first.
>
> This is a possibility.  However, it has to be done carefully to avoid
> problems.  There must be a limit on how high digging ability can be increase
> just like weapons/armor are effectively limited to +10.  I think +10 is
> ridiculously high for digging though, perhaps limiting it to 5 would be OK.

Actually, I have found on several occasions Gnomish Shovels (+6), but never
anything higher (both in umoria 4.87 and PC-MORIA 4.873).  So perhaps +6
should be the asymptotic limit, with decreasing chance of success for each
+, similar to enchanting weapon.

>Also, if this were allowed, then creatures should be allowed to 'disenchant'
>the digging ability of weapons, and there should be traps/scrolls/whatever
>that reduce the digging ability.  And there are probably some other changes
>needed as well that don't come immediately to mind.

Certainly - disenchanter creatures could affect digging ability, and (see
below) the enchantments on rings, etc.  Digging ability could also be reduced
by repeatedly digging through "hard" rock - say up to a 1% chance based on
what you are digging through.

>>You can't.  Period.  This is another feature I would like to see changed,
>>along with being able to increase the enchantment of rings, etc.
>
>I am very leary about adding this, because rings are permanent magic items.
>In particular, letting someone enchant a ring of speed to +2 or higher will
>seriously unbalance the game, as this is an incredible advantage for a
>player.

Again, allowing disenchanter creatures to affect this would overcome the
imbalance.  Also, there could be a small chance that an enchant item scroll
could destroy the item.  In fact, this should probably be the case even
for the existing enchant weapon/armor scrolls, since right now you have
*nothing* to lose by trying 100 times to get an extra + on weapons/armor.

Also, I still would like to see a very small chance that enchanting
weapons/armor would produce a special weapon (SD/SU/SE/SM/HA/DF) or
special armor (RC/RA/RL/RF/R).  Again, this would be counterbalanced
by the (slightly greater?) chance of destroying the item.  Perhaps,
too, disenchanter creatures could be allowed to remove the special
attributes.

Art Boyne, boyne@hplvla.hp.com

From ucbvax!decwrl!ames!think!samsung!usc!cs.utexas.edu!tut.cis.ohio-state.ed
Status: RO

Article 4487 of rec.games.moria:
Path: ucbvax!decwrl!ames!think!samsung!usc!cs.utexas.edu!tut.cis.ohio-state.e
>From: dtate@unix.cis.pitt.edu (David M Tate)
Newsgroups: rec.games.moria
Subject: Re: Enhancements to Umoria5.0 : the One Ring
Keywords: One Ring
Message-ID: <22578@unix.cis.pitt.edu>
Date: 27 Feb 90 16:46:31 GMT
References: <1990Feb22.005217.22427@cs.rochester.edu> <562@auvax.AthabascaU.CA
Reply-To: dtate@unix.cis.pitt.edu (David M Tate)
Distribution: all
Organization: Univ. of Pittsburgh, Comp & Info Services
Lines: 47

In article <562@auvax.AthabascaU.CA> kevinc@cs.AthabascaU.CA (Kevin Crocker)
>
>Remember, at least some of the Elven rings still existed, the Dwarven
>rings are presumably lost in the Mines of Moria, HINT!, HINT!, and of
>course the Nine walk abroad but are but wraiths of doom.
>
>All kinds of interesting thoughts appear.
>
Actually, if I remember my Ring-lore correctly, the seven were all taken by
Sauron.  The last was the ring of Thrain, which was taken from Thror (or was
it Thrain?) by Sauron in the dungeons of Dol Guldor.  No more Rings of Power
floating around in Moria.  The only rings still "available" are the three
rings (Narya, Nenya, Vilya) of the Elves, made by Celebrimbor. But I'm getting
pedantic...

I, too, would love to see an even-more-Tolkienish descendant of Moria...if you
get tired of Moria, maybe you could bash your way across Mirkwood to deal with
Smaug or the Necromancer.  Having Nazgul would add some spice, too.  And for
artifacts, you could find a palantir, which would let you look at any desired
portion of the level as if you were in the room(s), but from a distance.

Of course, I'm sure Jim Wilson is reading these postings and saying "Yeah, in
your dreams." :-)

I do like the idea of having more "special attribute" items, good and bad.
You could actually make the choices a lot harder by mixing them up: what would
*you* do if you found Boots [3,+7] (R) of Noise?  Or ego weapons with both
good and bad side effects (remember "Bessman's Flailing Hammer", in Larn?).
Items of invisibility would be great, too.

Any chance of getting Alter-ego Weapons?  A dagger (-2,-4) of Summon Undead?
Or something that *increases* susceptibility to certain breath/trap attacks,
like a ring (or armor) of Susceptibility to Cold/Fire/Poison/Acid/Lightning?

How about being able to buy lightning rods in the general store?  Plant one in
the floor, and all lightning attacks (dragon, wand, whatever) get drawn to it.
Just don't stand too close!

etc.



--
        David M. Tate       | "It made the basses of their being throb in
  dtate@unix.cis.pitt.edu   |  witching chords, and their thin blood pulse
                            |  pizzicati of Hosanna..."
 "A Man for all Seasonings" |                     -- Wallace Stevens


