s/CM_CARRY_GOLD/ACM_CARRY_GOLD/g
s/CM_CARRY_OBJ/BCM_CARRY_OBJ/g
s/CS_BR_FIRE/ACS_BR_FIRE/g
s/CS_BR_FROST/BCS_BR_FROST/g
s/CS_SUMMON_MON/ACS_SUMMON_MON/g
s/CS_SUMMON_UND/BCS_SUMMON_UND/g
s/CS_TEL_LONG/ACS_TEL_LONG/g
s/CS_TEL_SHORT/BCS_TEL_SHORT/g
s/CS_TEL_TO/CCS_TEL_TO/g
s/CUR_VERSION_MAJ/ACUR_VERSION_MAJ/g
s/CUR_VERSION_MIN/BCUR_VERSION_MIN/g
s/DUN_STR_DEN/ADUN_STR_DEN/g
s/DUN_STR_MAG/BDUN_STR_MAG/g
s/DUN_STR_MC/CDUN_STR_MC/g
s/DUN_STR_QC/DDUN_STR_QC/g
s/DUN_STR_QUA/EDUN_STR_QUA/g
s/DUN_STR_RNG/FDUN_STR_RNG/g
s/DUN_TUN_CHG/ADUN_TUN_CHG/g
s/DUN_TUN_CON/BDUN_TUN_CON/g
s/DUN_TUN_JCT/CDUN_TUN_JCT/g
s/DUN_TUN_PEN/DDUN_TUN_PEN/g
s/DUN_TUN_RND/EDUN_TUN_RND/g
s/ID_SHOW_HITDAM/AID_SHOW_HITDAM/g
s/ID_SHOW_P1/BID_SHOW_P1/g
s/INVEN_ARM/AINVEN_ARM/g
s/INVEN_ARRAY_SIZE/BINVEN_ARRAY_SIZE/g
s/INVEN_AUX/CINVEN_AUX/g
s/INVEN_HANDS/AINVEN_HANDS/g
s/INVEN_HEAD/BINVEN_HEAD/g
s/INVEN_LEFT/AINVEN_LEFT/g
s/INVEN_LIGHT/BINVEN_LIGHT/g
s/ITEM_GROUP_MAX/AITEM_GROUP_MAX/g
s/ITEM_GROUP_MIN/BITEM_GROUP_MIN/g
s/ITEM_NEVER_STACK_MAX/AITEM_NEVER_STACK_MAX/g
s/ITEM_NEVER_STACK_MIN/BITEM_NEVER_STACK_MIN/g
s/ITEM_SINGLE_STACK_MAX/AITEM_SINGLE_STACK_MAX/g
s/ITEM_SINGLE_STACK_MIN/BITEM_SINGLE_STACK_MIN/g
s/MAX_CAVE_FLOOR/AMAX_CAVE_FLOOR/g
s/MAX_CAVE_ROOM/BMAX_CAVE_ROOM/g
s/MAX_MALLOC/AMAX_MALLOC/g
s/AMAX_MALLOC_CHANCE/BMAX_MALLOC_CHANCE/g
s/MAX_MONS_LEVEL/AMAX_MONS_LEVEL/g
s/MAX_MON_MULT/BMAX_MON_MULT/g
s/MAX_MON_NATTACK/CMAX_MON_NATTACK/g
s/MAX_OBJECTS/AMAX_OBJECTS/g
s/MAX_OBJ_LEVEL/BMAX_OBJ_LEVEL/g
s/MIN_MALLOC_LEVEL/AMIN_MALLOC_LEVEL/g
s/MIN_MALLOC_TD/BMIN_MALLOC_TD/g
s/MIN_MALLOC_TN/CMIN_MALLOC_TN/g
s/MORIA_HELP/AMORIA_HELP/g
s/MORIA_HOU/BMORIA_HOU/g
s/MORIA_ORIG_HELP/AMORIA_ORIG_HELP/g
s/MORIA_OWIZ_HELP/BMORIA_OWIZ_HELP/g
s/MORIA_SAV/AMORIA_SAV/g
s/AMORIA_SAVE/BMORIA_SAVE/g
s/AMORIA_SAV_NAME/CMORIA_SAV_NAME/g
s/MORIA_TOP/AMORIA_TOP/g
s/AMORIA_TOP_NAME/BMORIA_TOP_NAME/g
s/MORIA_WELCOME/AMORIA_WELCOME/g
s/MORIA_WIZ_HELP/BMORIA_WIZ_HELP/g
s/NORMAL_TABLE_SD/ANORMAL_TABLE_SD/g
s/NORMAL_TABLE_SIZE/BNORMAL_TABLE_SIZE/g
s/OBJ_BASE_MAGIC/AOBJ_BASE_MAGIC/g
s/OBJ_BASE_MAX/BOBJ_BASE_MAX/g
s/OBJ_DIV_CURSED/AOBJ_DIV_CURSED/g
s/OBJ_DIV_SPECIAL/BOBJ_DIV_SPECIAL/g
s/OBJ_STD_ADJ/AOBJ_STD_ADJ/g
s/OBJ_STD_MIN/BOBJ_STD_MIN/g
s/PLAYER_EXIT_PAUSE/APLAYER_EXIT_PAUSE/g
s/PLAYER_FOOD_ALERT/BPLAYER_FOOD_ALERT/g
s/PLAYER_FOOD_FAINT/CPLAYER_FOOD_FAINT/g
s/PLAYER_FOOD_FULL/DPLAYER_FOOD_FULL/g
s/PLAYER_FOOD_MAX/EPLAYER_FOOD_MAX/g
s/PLAYER_FOOD_WEAK/FPLAYER_FOOD_WEAK/g
s/PLAYER_REGEN_FAINT/GPLAYER_REGEN_FAINT/g
s/PLAYER_REGEN_HPBASE/HPLAYER_REGEN_HPBASE/g
s/PLAYER_REGEN_MNBASE/IPLAYER_REGEN_MNBASE/g
s/PLAYER_REGEN_NORMAL/JPLAYER_REGEN_NORMAL/g
s/PLAYER_REGEN_WEAK/KPLAYER_REGEN_WEAK/g
s/PLAYER_WEIGHT_CAP/LPLAYER_WEIGHT_CAP/g
s/SCREEN_HEIGHT/ASCREEN_HEIGHT/g
s/SCREEN_WIDTH/BSCREEN_WIDTH/g
s/SN_SLAYING/ASN_SLAYING/g
s/SN_SLAY_ANIMAL/BSN_SLAY_ANIMAL/g
s/SN_SLAY_EVIL/CSN_SLAY_EVIL/g
s/SN_SLOWNESS/ASN_SLOWNESS/g
s/SN_SLOW_DESCENT/BSN_SLOW_DESCENT/g
s/STORE_MAX_INVEN/ASTORE_MAX_INVEN/g
s/STORE_MIN_INVEN/BSTORE_MIN_INVEN/g
s/TR_RES_ACID/ATR_RES_ACID/g
s/TR_RES_COLD/BTR_RES_COLD/g
s/TR_RES_FIRE/CTR_RES_FIRE/g
s/TR_RES_LIGHT/DTR_RES_LIGHT/g
s/TR_SLAY_ANIMAL/ATR_SLAY_ANIMAL/g
s/TR_SLAY_DRAGON/BTR_SLAY_DRAGON/g
s/TR_SLAY_EVIL/CTR_SLAY_EVIL/g
s/TR_SLAY_UNDEAD/DTR_SLAY_UNDEAD/g
s/TV_MAX_ENCHANT/ATV_MAX_ENCHANT/g
s/TV_MAX_OBJECT/BTV_MAX_OBJECT/g
s/TV_MAX_PICK_UP/CTV_MAX_PICK_UP/g
s/TV_MAX_VISIBLE/DTV_MAX_VISIBLE/g
s/TV_MAX_WEAR/ETV_MAX_WEAR/g
s/TV_MIN_DOORS/ATV_MIN_DOORS/g
s/TV_MIN_ENCHANT/BTV_MIN_ENCHANT/g
s/TV_MIN_VISIBLE/CTV_MIN_VISIBLE/g
s/TV_MIN_WEAR/DTV_MIN_WEAR/g
s/TV_POTION1/ATV_POTION1/g
s/TV_POTION2/BTV_POTION2/g
s/TV_SCROLL1/ATV_SCROLL1/g
s/TV_SCROLL2/BTV_SCROLL2/g
s/WIN_MON_APPEAR/AWIN_MON_APPEAR/g
s/WIN_MON_TOT/BWIN_MON_TOT/g
s/aggravate/Aaggravate/g
s/Aaggravate_monster/Baggravate_monster/g
s/attack_blows/Aattack_blows/g
s/attack_desc/Battack_desc/g
s/attack_dice/Cattack_dice/g
s/attack_sides/Dattack_sides/g
s/attack_type/Eattack_type/g
s/background/Abackground/g
s/Abackground_type/Bbackground_type/g
s/change_character/Achange_character/g
s/change_name/Bchange_name/g
s/change_speed/Cchange_speed/g
s/change_trap/Dchange_trap/g
s/character_generated/Acharacter_generated/g
s/character_saved/Bcharacter_saved/g
s/confuse_monster/Aconfuse_monster/g
s/confused/Bconfused/g
s/create_character/Acreate_character/g
s/create_food/Bcreate_food/g
s/creature_type/Acreature_type/g
s/creatures/Bcreatures/g
s/default_dir/Adefault_dir/g
s/default_signals/Bdefault_signals/g
s/delete_monster/Adelete_monster/g
s/delete_object/Bdelete_object/g
s/detect_evil/Adetect_evil/g
s/detect_inv/Bdetect_inv/g
s/detect_inv2/Cdetect_inv2/g
s/detect_invisible/Ddetect_invisible/g
s/detect_monsters/Edetect_monsters/g
s/detect_object/Fdetect_object/g
s/detect_sdoor/Gdetect_sdoor/g
s/detect_trap/Hdetect_trap/g
s/detect_treasure/Idetect_treasure/g
s/disarm_all/Adisarm_all/g
s/disarm_trap/Bdisarm_trap/g
s/insert_lnum/Ainsert_lnum/g
s/insert_num/Binsert_num/g
s/insert_str/Cinsert_str/g
s/insult_cur/Ainsult_cur/g
s/insult_max/Binsult_max/g
s/inven_carry/Ainven_carry/g
s/inven_check_num/Binven_check_num/g
s/inven_check_weight/Cinven_check_weight/g
s/inven_command/Dinven_command/g
s/inven_ctr/Einven_ctr/g
s/inven_damage/Ainven_damage/g
s/inven_destroy/Binven_destroy/g
s/inven_drop/Cinven_drop/g
s/inven_throw/Ainven_throw/g
s/inven_type/Binven_type/g
s/log_max_dlv/Alog_max_dlv/g
s/log_max_exp/Blog_max_exp/g
s/magic_shop/Amagic_shop/g
s/magic_spell/Bmagic_spell/g
s/max_panel_cols/Amax_panel_cols/g
s/max_panel_rows/Bmax_panel_rows/g
s/monster_attacks/Amonster_attacks/g
s/monster_death/Bmonster_death/g
s/monster_name/Cmonster_name/g
s/monster_type/Dmonster_type/g
s/move_cursor/Amove_cursor/g
s/Amove_cursor_relative/Bmove_cursor_relative/g
s/msdos_init/Amsdos_init/g
s/msdos_intro/Bmsdos_intro/g
s/next_to_corr/Anext_to_corr/g
s/next_to_wall/Bnext_to_wall/g
s/next_to_walls/Cnext_to_walls/g
s/object_ident/Aobject_ident/g
s/object_list/Bobject_list/g
s/panel_col/Apanel_col/g
s/Apanel_col_max/Bpanel_col_max/g
s/Apanel_col_min/Cpanel_col_min/g
s/Apanel_col_prt/Dpanel_col_prt/g
s/panel_contains/Epanel_contains/g
s/panel_row/Apanel_row/g
s/Apanel_row_max/Bpanel_row_max/g
s/Apanel_row_min/Cpanel_row_min/g
s/Apanel_row_prt/Dpanel_row_prt/g
s/player_exp/Aplayer_exp/g
s/player_hp/Bplayer_hp/g
s/player_init/Cplayer_init/g
s/player_light/Dplayer_light/g
s/player_saves/Eplayer_saves/g
s/player_type/Fplayer_type/g
s/protect_evil/Aprotect_evil/g
s/protection/Bprotection/g
s/prt_stat/Aprt_stat/g
s/Aprt_stat_block/Bprt_stat_block/g
s/Aprt_state/Cprt_state/g
s/put_misc1/Aput_misc1/g
s/put_misc2/Bput_misc2/g
s/put_misc3/Cput_misc3/g
s/remove_curse/Aremove_curse/g
s/remove_fear/Bremove_fear/g
s/resist_cold/Aresist_cold/g
s/resist_heat/Bresist_heat/g
s/restore_level/Arestore_level/g
s/restore_screen/Brestore_screen/g
s/restore_signals/Crestore_signals/g
s/restore_term/Drestore_term/g
s/screen_change/Ascreen_change/g
s/screen_map/Bscreen_map/g
s/search_flag/Asearch_flag/g
s/search_off/Bsearch_off/g
s/search_on/Csearch_on/g
s/set_acid_affect/Aset_acid_affect/g
s/set_acid_destroy/Bset_acid_destroy/g
s/set_corr/Aset_corr/g
s/Aset_corrodes/Bset_corrodes/g
s/sleep_monster/Asleep_monster/g
s/Asleep_monsters1/Bsleep_monsters1/g
s/Asleep_monsters2/Csleep_monsters2/g
s/speed_monster/Aspeed_monster/g
s/Aspeed_monsters/Bspeed_monsters/g
s/store_bought/Astore_bought/g
s/Astore_bought_p/Bstore_bought_p/g
s/store_buy/Cstore_buy/g
s/store_carry/Astore_carry/g
s/store_check_num/Bstore_check_num/g
s/store_choice/Cstore_choice/g
s/store_ctr/Dstore_ctr/g
s/store_init/Astore_init/g
s/store_inven/Bstore_inven/g
s/summon_monster/Asummon_monster/g
s/summon_object/Bsummon_object/g
s/summon_undead/Csummon_undead/g
s/sustain_chr/Asustain_chr/g
s/sustain_con/Bsustain_con/g
s/sustain_dex/Csustain_dex/g
s/sustain_int/Dsustain_int/g
s/sustain_str/Esustain_str/g
s/sustain_wis/Fsustain_wis/g
s/td_destroy/Atd_destroy/g
s/Atd_destroy2/Btd_destroy2/g
s/teleport/Ateleport/g
s/Ateleport_away/Bteleport_away/g
s/Ateleport_flag/Cteleport_flag/g
s/Ateleport_monster/Dteleport_monster/g
s/Ateleport_to/Eteleport_to/g
s/wizard_create/Awizard_create/g
s/wizard_light/Bwizard_light/g
s/generate_cave/Bgenerate_cave/g
s/compact_monsters/Acompact_monsters/g
s/compact_objects/Bcompact_objects/g
s/spell_choice/Aspell_choice/g
s/spell_type/Bspell_type/g
s/spell_names/Cspell_names/g
s/spell_worked/Dspell_worked/g
s/spell_order/Espell_order/g
s/spell_chance/Fspell_chance/g
s/spell_char/Gspell_char/g
s/spell_forgotten/Hspell_forgotten/g
s/spell_learned/Ispell_learned/g
s/spell_worked/Jspell_worked/g
s/place_monster/Aplace_monster/g
s/place_boundary/Bplace_boundary/g
s/place_streamer/Cplace_streamer/g
s/place_open_door/Dplace_open_door/g
s/place_broken_door/Eplace_broken_door/g
s/place_closed_door/Fplace_closed_door/g
s/place_locked_door/Gplace_locked_door/g
s/place_stuck_door/Hplace_stuck_door/g
s/place_secret_door/Iplace_secret_door/g
s/place_door/Jplace_door/g
s/place_up_stairs/Kplace_up_stairs/g
s/place_down_stairs/Lplace_down_stairs/g
s/place_stairs/Mplace_stairs/g
s/place_gold/Nplace_gold/g
s/place_trap/Oplace_trap/g
s/place_object/Pplace_object/g
s/place_win_monster/Qplace_win_monster/g
s/place_rubble/Rplace_rubble/g
s/build_type1/Abuild_type1/g
s/build_type2/Bbuild_type2/g
s/build_type3/Cbuild_type3/g
s/version_maj/Aversion_maj/g
s/version_min/Bversion_min/g
s/rd_shorts/Ard_shorts/g
s/wr_shorts/Awr_shorts/g
s/purchase_haggle/Bpurchase_haggle/g
s/prt_comment1/Aprt_comment1/g
s/prt_comment2/Bprt_comment2/g
s/prt_comment3/Cprt_comment3/g
s/prt_comment4/Dprt_comment4/g
s/prt_comment5/Eprt_comment5/g
s/prt_comment6/Fprt_comment6/g
s/comment1/Acomment1/g
s/comment2a/Bcomment2a/g
s/comment2b/Ccomment2b/g
s/comment3a/Dcomment3a/g
s/comment3b/Ecomment3b/g
s/comment4a/Fcomment4a/g
s/comment4b/Gcomment4b/g
s/comment5/Hcomment5/g
s/display_char/Adisplay_char/g
s/display_scores/Bdisplay_scores/g
s/display_commands/Cdisplay_commands/g
s/display_inventory/Ddisplay_inventory/g
s/display_cost/Edisplay_cost/g
s/display_store/Fdisplay_cost/g
s/signal_handler/Asignal_handler/g
s/new_mana/Anew_mana/g
s/Anew_mana_frac/Bnew_mana_frac/g
s/find_breakleft/Afind_breakleft/g
s/find_breakright/Bfind_breakright/g
s/map_diag1/Amap_diag1/g
s/map_diag2/Bmap_diag2/g
s/You feel Bconfused/You feel confused/g
s/appears Bconfused/appears confused/g
s/rune of Bprotection/rune of protection/g
s/You feel less Bconfused now/You feel less confused now/g
s/error in Bmove_cursor_relative/error in move_cursor_relative/g
s/You are too Bconfused/You are too confused/g
s/You hit a Ateleport trap!/You hit a teleport trap!/g
s/You are Bconfused/You are confused/g
s/kill weaker Bcreatures/kill weaker creatures/g
s/Ateleport short distances/teleport short distances/g
s/Ateleport long distances/teleport long distances/g
s/Ateleport its prey/teleport its prey/g
s/of these Bcreatures/of these creatures/g
s/invisible Bcreatures!/invisible creatures!/g
s/envelops several Bcreatures!/envelops several creatures!/g
s/You are Bconfused/You are confused/g
