#!/bin/sh

#
# this shell script will generate a formated list of what all weapons will
# do

in=$1
out=`basename $in .in`.out

echo "          Name                | Mblow | Blows | wt ratio | dam | w/ critical |" >$out

calchits <$in \ |
   sed -n -e "2,45p" | cut -c10-10,14-17,19-30,35-45,49-53,57- | \
   paste -d" " mkallwpn.lst - | sort -t"|" -bnr +5 -6 >>$out

